---
tls_certs_certs:
  - ca_content: '{{ lookup("ansible.builtin.file", elasticsearch_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", elasticsearch_ca_key_path) }}'
    cert_path: '{{ elasticsearch_cert_path }}'
    key_path: '{{ elasticsearch_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", elasticsearch_transport_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", elasticsearch_transport_ca_key_path) }}'
    cert_path: '{{ elasticsearch_transport_cert_path }}'
    key_path: '{{ elasticsearch_transport_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", filebeat_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", filebeat_ca_key_path) }}'
    cert_path: '{{ filebeat_cert_path }}'
    key_path: '{{ filebeat_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", kafka_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", kafka_ca_key_path) }}'
    cert_path: '{{ kafka_cert_path }}'
    key_path: '{{ kafka_key_path }}'
  - ca_content: '{{ lookup("ansible.builtin.file", kibana_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", kibana_ca_key_path) }}'
    cert_path: '{{ kibana_cert_path }}'
    key_path: '{{ kibana_key_path }}'
    not_after: '{{ kibana_cert_not_after }}'
    not_before: '{{ kibana_cert_not_before }}'
  - ca_content: '{{ lookup("ansible.builtin.file", logstash_ca_cert_path) }}'
    ca_key_content: '{{ lookup("ansible.builtin.file", logstash_ca_key_path) }}'
    cert_path: '{{ logstash_cert_path }}'
    key_path: '{{ logstash_key_path }}'
...
