---
system_groups_list:
  - name: '{{ kafka_group }}'
system_users_list:
  - name: '{{ kafka_user }}'
    password: 'x'
    group: '{{ kafka_group }}'
    comment: Apache Kafka open-source distributed event streaming platform
    home: '{{ kafka_home_dir }}'
...
