---
- name: Gather distribution facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - 'distribution'
  tags: [redis_repo]

- name: Download redis repository key
  ansible.builtin.get_url:
    url: '{{ redis_repo_signing_key }}'
    dest: '{{ redis_repo_signing_key_path }}'
    checksum: '{{ redis_repo_signing_key_checksum }}'
    owner: root
    group: root
    mode: '0644'
  tags: [redis_repo]

- name: Add redis repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by={{ redis_repo_signing_key_path }}]
      {{ redis_repo_mirror }}
      {{ ansible_facts['distribution_release'] }}
      main
    filename: redis
    state: present
  tags: [redis_repo]
...
