---
- name: Install JAVA runtime
  ansible.builtin.apt:
    name: default-jre-headless
    update_cache: true
    cache_valid_time: 3600
    state: present
  retries: 10
  delay: 10

- name: Create kafka directory
  ansible.builtin.file:
    path: '{{ kafka_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download and unarchive kafka release binary
  ansible.builtin.unarchive:
    src: '{{ kafka_download_url }}'
    dest: '{{ kafka_path }}'
    remote_src: true
    creates: '{{ kafka_path }}/bin/kafka-server-start.sh'
    extra_opts: --strip-components=1
    owner: root
    group: root
...
